#pragma config(Sensor, in1,    Arm,            sensorPotentiometer)
#pragma config(Sensor, dgtl12, Launcher,       sensorTouch)
#pragma config(Motor,  port1,           Claw,          tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           LauncherOne,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           LauncherTwo,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           LauncherThree, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           LeftWheels,    tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port6,           RightWheels,   tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           LiftOne,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           LiftTwo,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           LiftThree,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          Spool,         tmotorNone, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

void LauncherDown(int DownPower);
void MoveClaw (int ClawPower);
void StopAll();
void MoveSpool(int SpoolPower);

//task Move();
task Lift();
task HoldPower();
//gloabal variable
bool isUp = true;
bool readSensor = true;


/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
	// Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{
	// .....................................................................................
	// Insert user code here.
	// .....................................................................................

}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{
	//startTask (Move);

	while (true)
	{

		if (vexRT[Btn8U] == 1)
		{
			LauncherDown(127);
			wait1Msec(0);
			waitUntil(SensorValue[Launcher]==1);
			{
				wait1Msec(80);
				LauncherDown(20);
				if (vexRT[Btn8D] ==1)
				{
					LauncherDown(100);
					wait1Msec(500);
					LauncherDown(0);
				}
			}

			// LauncherDown(40);
		}
		if (vexRT[Btn8D] == 1)
		{
			LauncherDown(0);
			wait1Msec(10);
		}
		if (vexRT[Btn6U] == 1)
		{
			MoveClaw(-120);
			wait1Msec(10);
			if (vexRT[Btn6U] == 0)
			{
				MoveClaw(-60);
			}
		}
		if (vexRT[Btn6D] == 1)
		{
			MoveClaw(120);
			wait1Msec(10);
		}
		if (vexRT[Btn8L] == 1)
		{
			StopAll();
		}
		if (vexRT[Btn7U] == 1)
		{
			isUp = true;
			startTask (Lift);
		}
		if (vexRT[Btn7D] == 1)
		{
			isUp = false;
			startTask (Lift);
		}
		if (vexRT[Btn5U] == 1)
		{
			MoveSpool(-80);
			wait1Msec(10);
			if (vexRT[Btn5U] == 0)
			{
				MoveSpool(0);
				wait1Msec(10);
			}
		}
		if (vexRT[Btn5D] == 1)
		{
			MoveSpool(80);
			wait1Msec(10);
			if (vexRT[Btn5D] == 0)
			{
				MoveSpool(0);
				wait1Msec(10);
			}
		}

		if (SensorValue[Arm] > 3000){
			startTask (HoldPower);
			readSensor = true;

			if (vexRT[Btn7D] == 1)
			{
				readSensor = false;
			}
		}
		/*if (SensorValue[Arm] < 800){
		motor[LiftOne]= 50;
		motor[LiftTwo]= 50;
		motor[LiftThree]= 50;

		}*/
	}
}

void LauncherDown(int DownPower)
{
	motor[LauncherOne] = DownPower;
	motor[LauncherTwo] = DownPower;
	motor[LauncherThree] = DownPower;
}

void MoveClaw (int ClawPower)
{
	motor[Claw] = ClawPower;
}

void StopAll()
{
	motor[Claw] = 0;
	motor[LauncherOne] = 0;
	motor[LauncherTwo] = 0;
	motor[LauncherThree] = 0;
}

void MoveSpool (int SpoolPower)
{
	motor[Spool] = SpoolPower;
}

task Lift()
{
	int power = 100;
	if (isUp == true)
	{
		power = -100;
	}
	motor[LiftOne] =	power;
	motor[LiftTwo] = power;
	motor[LiftThree] = power;
}

/*task Move ()
{
while (true)
{
motor[LeftWheels] = vexRT[Ch3] + vexRT[Ch1];
motor[RightWheels] = vexRT[Ch3] - vexRT[Ch1];

EndTimeSlice();
}
}*/

task HoldPower()
{
	int power = 0;
	if (readSensor == true)
	{
		power = -50;
	}
	motor[LiftOne] = power;
	motor[LiftTwo] = power;
	motor[LiftThree] = power;
}
