#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, dgtl1,  Launcher1_Loaded, sensorTouch)
#pragma config(Sensor, I2C_1,  Launcher1_Position, sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           Dispenser,     tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           Launcher1,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           Launcher2,     tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
  // Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{
  // .....................................................................................
  // Insert user code here.
  // .....................................................................................

	AutonomousCodePlaceholderForTesting();  // Remove this function call once you have "real" code.
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////



task LauncherUp();
task LauncherStop();
task LauncherDown();

task usercontrol()
{
	// User control code here, inside the loop

	while (true)
	{

		int btn8u = vexRT[Btn8U]; // Fast Launcher
		int btn8d = vexRT[Btn8D]; // Slow Launcher
		int btn8l = vexRT[Btn8L]; // Slow Launcher
		//int btn8r = vexRT[Btn8R]; // Slow Launcher

		//int power8 = 100; // shift

		int power8 = 90; // shift
		int powerDispenser = 12;

		motor[Dispenser] = -btn8d * powerDispenser;
		motor[Launcher1] = -btn8u * power8 + btn8d * power8;
		motor[Launcher2] = -btn8u * power8 + btn8d * power8;

		/*
		if (btn8d == 1)
		{
			stopTask(LauncherUp);

			wait1Msec(10);
			startTask(LauncherDown);
		}
		else if (btn8u == 1)
		{
			stopTask(LauncherDown);

			wait1Msec(10);
			startTask(LauncherUp);
		}
		else if (btn8r == 1)
		{
			stopTask(LauncherDown);
			stopTask(LauncherUp);

			wait1Msec(10);
			startTask(LauncherStop);
		}
		*/

	}
}


task LauncherUp()
{// T3
  //stopTask(LauncherStop);

	int originalPower = -110;
	int primaryPower = originalPower;

	motor[Launcher1] = primaryPower;
	motor[Launcher2] = primaryPower;

	wait1Msec(70);

	//originalPower =  -19;
	//primaryPower = originalPower;

	//motor[Launcher1] = primaryPower;
	//motor[Launcher2] = primaryPower;
	//motor[Launcher3] = primaryPower;


  startTask(LauncherStop);
}

task LauncherDown()
{// T3
	int originalPower = 100;
	int primaryPower = originalPower;

	motor[Launcher1] = primaryPower;
	motor[Launcher2] = primaryPower;

	wait1Msec(200);

	originalPower =  20;
	primaryPower = originalPower;

	motor[Launcher1] = primaryPower;
	motor[Launcher2] = primaryPower;
}


task LauncherStop()
{
	int power = 0;

	motor[Launcher1] = power;
	motor[Launcher2] = power;
}
