#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, dgtl1,  Launcher1_Loaded, sensorTouch)
#pragma config(Sensor, I2C_1,  Launcher1_I2C,  sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  Loader1_I2C,    sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           Loader1,       tmotorVex393_HBridge, openLoop, encoderPort, I2C_2)
#pragma config(Motor,  port2,           Launcher1_H,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           Launcher1_L,   tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_1)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
  // Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{
  // .....................................................................................
  // Insert user code here.
  // .....................................................................................

	AutonomousCodePlaceholderForTesting();  // Remove this function call once you have "real" code.
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task LauncherUp();
task LauncherStop();
task LauncherDown();


void LauncherDown_Helper();
void LauncherStop_Helper();

task usercontrol()
{
	// User control code here, inside the loop

	while (true)
	{

		int btn8u = vexRT[Btn8U]; // Fast Launcher
		int btn8d = vexRT[Btn8D]; // Slow Launcher
		int btn8l = vexRT[Btn8L]; // Slow Launcher
		//int btn8r = vexRT[Btn8R]; // Slow Launcher

		//int power8 = 100; // shift

		//int powerLauncher = 90; // shift
		//int powerLoader = 12;

		////motor[Loader1] = -btn8d * powerLoader;
		//motor[Launcher1_H] = -btn8u * powerLauncher;
		//motor[Launcher1_L] = -btn8u * powerLauncher;


		if (btn8d == 1)
		{
			//stopTask(LauncherUp);

			//wait1Msec(10);
			startTask(LauncherDown);
		}
	}
}

task LauncherDown()
{//
	LauncherDown_Helper();
}

void LauncherDown_Helper()
{// T3


	// Turn right to the center
	nMotorEncoder(Launcher1_L) = 0;

	int originalPower = 100;
	int primaryPower = originalPower;

	motor[Launcher1_H] = primaryPower;
	motor[Launcher1_L] = primaryPower;

	writeDebugStreamLine("LauncherDown_Helper) #1 launcherPosition :%d", abs(nMotorEncoder(Launcher1_L)));

	waitUntil(abs(nMotorEncoder(Launcher1_L)) >= 200);

	writeDebugStreamLine("LauncherDown_Helper) #2 launcherPosition :%d", abs(nMotorEncoder(Launcher1_L)));


	originalPower = 15;
	primaryPower = originalPower;

	motor[Launcher1_H] = primaryPower;
	motor[Launcher1_L] = primaryPower;


	nMotorEncoder(Loader1) = 0;
	int powerLoader = -45;
	motor[Loader1] = powerLoader;

	waitUntil(abs(nMotorEncoder(Loader1)) >= 90 || SensorValue[Launcher1_Loaded] == 1);
	
	writeDebugStreamLine("LauncherDown_Helper) 00 Launcher1_Loaded :%d", SensorValue[Launcher1_Loaded]);
	writeDebugStreamLine("LauncherDown_Helper) 00 Loader1 :%d", abs(nMotorEncoder(Loader1)));

	motor[Loader1] = 0;
	
	clearTimer(T3);
	waitUntil(SensorValue[Launcher1_Loaded] == 1 || time1[T3] > 1000);
	
	if (time1[T3] > 1000)
	{
		startTask(LauncherStop);
		return;
	}

	powerLoader = 55;
	motor[Loader1] = powerLoader;

	
	nMotorEncoder(Loader1) = 0;
	waitUntil(abs(nMotorEncoder(Loader1)) >= 20);
	motor[Loader1] = 0;
	
	
	//wait1Msec(10);

	//powerLoader = 80;
	//motor[Loader1] = powerLoader;
	//wait1Msec(100);

	//motor[Loader1] = 0;

	//writeDebugStreamLine("LauncherDown_Helper) 01 Launcher1_Loaded :%d", SensorValue[Launcher1_Loaded]);




	//wait1Msec(100);

	//motor[Loader1] = 0;
	//wait1Msec(50);

	//powerLoader = 20;
	//motor[Loader1] = powerLoader;
	//wait1Msec(80);


	//motor[Loader1] = 0;


	wait1Msec(200);
	originalPower = 100;
	primaryPower = originalPower;

	motor[Launcher1_H] = primaryPower;
	motor[Launcher1_L] = primaryPower;


	writeDebugStreamLine("LauncherDown_Helper) #3 launcherPosition :%d", abs(nMotorEncoder(Launcher1_L)));

	waitUntil(SensorValue[Launcher1_Loaded] == 0 || abs(nMotorEncoder(Launcher1_L)) >= 509);

	writeDebugStreamLine("LauncherDown_Helper) #4 launcherPosition :%d", abs(nMotorEncoder(Launcher1_L)));

	//motor[Loader1] = 0;

  startTask(LauncherStop);
  
  	wait1Msec(10);
	originalPower = -30;
	primaryPower = originalPower;

	motor[Launcher1_H] = primaryPower;
	motor[Launcher1_L] = primaryPower;
		
	waitUntil(abs(nMotorEncoder(Launcher1_L)) < 522);
	writeDebugStreamLine("LauncherDown_Helper) #5 launcherPosition :%d", abs(nMotorEncoder(Launcher1_L)));

	startTask(LauncherStop);
  
	
}

task LauncherUp()
{// T3
  //stopTask(LauncherStop);

	int originalPower = -110;
	int primaryPower = originalPower;

	motor[Launcher1_H] = primaryPower;
	motor[Launcher1_L] = primaryPower;

	wait1Msec(70);

	//originalPower =  -19;
	//primaryPower = originalPower;

	//motor[Launcher1] = primaryPower;
	//motor[Launcher2] = primaryPower;
	//motor[Launcher3] = primaryPower;


  startTask(LauncherStop);
}

task LauncherStop()
{
	LauncherStop_Helper();
}

void LauncherStop_Helper()
{
	int power = 0;

	motor[Launcher1_H] = power;
	motor[Launcher1_L] = power;
}
